markdown: kramdown
encoding: utf-8
baseurl: "https://onlinegurucool.github.io/"
port: 3030 # port for localhost

sass:
  sass_dir: styles
  sourcemap: :true
  style: compact


exclude: ['_site','static-pages','.sass-cache','design','designs']

# SEO
domain: "https://onlinegurucool.github.io"
metadescription: "Online GuruCool is eLearning platform. Where you can find all tips & tricks about website developement languages such as HTML CSS SASS NodeJS Expressjs MySql etc."
metakeyword: "YouTube, Online , GuruCool, Tutorials, Sass Tutorial, Hindi Tutorial, web Developement, HTML Tutuorial, tuorials in hindi, reginal language, elearning platform"
metaImg: "images/site-seo.png"  #this must be 1200x650
title: "Online GuruCool"

# Tracking
googleAnalyticsId :  # eg. 'UA-67098409-1' to genrate this code visit on analytics.google.com
